package com.sunbird.entity.model.DTO;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.List;
import java.util.Map;

@Getter
@Setter
public class EntityDataDTO {

    private Integer id; // generated by DB, optional in request
    private String type;
    private String name;
    private String description;
    private Map<String, Object> additionalProperties;
    private String status;
    private String source;
    private String level;
    private int levelId;
    private Date createdDate;
    private String createdBy;
    private Date updatedDate;
    private String updatedBy;
    private Date reviewedDate;
    private String reviewedBy;
    private Map<String, Object> translation;
    private String code;

    /**
     * Children can be either other entities or a generic Map structure.
     * This mirrors the @Transient field in Entity.
     */
    private List<Map<String, Object>> children;
}
